#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Customize to your needs...
#if not running interactively, do not do anything
[[ $- != *i* ]] && return
[[ -z "$TMUX" ]] && exec tmux

alias boot-code-noauth='~/code-server/code-server --allow-http --no-auth'
alias boot-code='~/code-server/code-server --allow-http'
alias pushd='pushd ./'

cdls()
{
  \cd "$@" && ls -la
}
alias cd="cdls"

PURE_PROMPT_SYMBOL='>'

#GnuPG2
pgrep -q gpg-agent || eval $(gpg-agent --daemon --write-env-file ${HOME}/.gpg-agent-info)
[ -f ${HOME}/.gpg-agent-info ] && source ${HOME}/.gpg-agent-info
export GPG_AGENT_INFO
export GPG_TTY=`tty`
